import math as m
import numpy as np

#Constants
earthGravConst = 3.986e14 # Earth-Gravity Constant in m3/s2
earthRadius = 6378 # Radius of Earth in Km.

FireSat = {
            "M": 215, #Mass [kg]
            "Iz": 90, #Moment of Inertia [Kg.m2] Ix = Iz
            "Iy" : 60, #Moment of Inertia [Kg.m2]
            "orbitAlt" : 700, #Alt [Km], Circular Orbit
            "slewRate" : 1, #0.1 [deg/s]
            "pointingAcc" : 0.1 # [deg]
    }

WinSAT = {
            "M": 133, #Mass [kg]
            "Iz": 96, #Moment of Inertia [Kg.m2] Ix = Iz
            "Iy" : 60, #Moment of Inertia [Kg.m2]
            "orbitAlt" : 700, #Alt [Km], Circular Orbit
            "slewRate" : 1, #0.1 [deg/s]
            "pointingAcc" : 0.1 # [deg]
    }

# REFER TO TABLE 11.9A IN SMAD FOR LIST OF EQUATIONS

"""MAX GRAVITY TORQUE GENERATED BY GRAVITY GRADIENT DISTURBANCE"""

def GG(sat):
    orbitRadius = (earthRadius+sat['orbitAlt'])*1000
    T = ((3*earthGravConst)/(2*((orbitRadius)**3))) * (sat["Iz"] - sat["Iy"]) * (np.sin(np.deg2rad(2*sat["slewRate"])))
    return T

print GG(WinSAT)