import math as m
import numpy as np

Mu = 3.986e14 # Earth-Gravity Constant in m3/s2
R = 6378 # Radius of Earth in Km.

FireSat = {
            "M": 215, #Mass in kg
            "Iz": 90, #Moment of Inertia in Kg.m2 Ix = Iz
            "Iy" : 60, #Moment of Inertia in Kg.m2
            "Orbit_Alt" : 700, #Alt in Km,Circular
            "Slew_Rate" : 1, #Less than 0.1 deg/s
            "Pointing_Acc" : 0.1 # in Degree

            }

CubeSat = {
            "M": 0, #Mass in kg
            "Iz": 0, #Moment of Inertia in Kg.m2 Ix = Iz
            "Iy" : 0, #Moment of Inertia in Kg.m2
            "Orbit_Alt" : 0, #Alt in Km,Circular
            "Slew_Rate" : 0, #Less than 0.1 deg/s
            "Pointing_Acc" : 0 # in Degree

            }

# REFER TO TABLE 11.9A IN SMAD FOR LIST OF EQUATIONS

"""MAX GRAVITY TORQUE GENERATED BY GRAVITY GRADIENT DISTURBANCE"""
def GG():
    Orb_R= (R+700)*1000
    T = ((3*Mu)/(2*((Orb_R)**3)))* (FireSat["Iz"] - FireSat["Iy"])*(np.sin(np.deg2rad(2*FireSat["Slew_Rate"])))
    print(T)

GG()
